apiVersion: v1
kind: Service
metadata:
  name: "{{ template "harbor.jobservice" . }}"
  labels: {{ include "harbor.labels" . | nindent 4 }}
spec:
  ports:
    - port: 80
      targetPort: http
  selector:
    {{- include "harbor.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: jobservice
