{{- if .Values.chartmuseum.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "harbor.chartmuseum" . }}-secret"
  labels:
    {{ include "harbor.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if and .Values.chartmuseum.useRedisCache }}
  CACHE_REDIS_PASSWORD: {{ include "harbor.redis.rawPassword" . | b64enc | quote }}
  {{- end }}
  {{- $storage := .Values.persistence.imageChartStorage }}
  {{- $storageType := $storage.type }}
  {{- if eq $storageType "azure" }}
  AZURE_STORAGE_ACCESS_KEY: {{ $storage.azure.accountkey | b64enc | quote }}
  {{- else if eq $storageType "gcs" }}
  GCS_KEY_DATA: {{ $storage.gcs.encodedkey | b64enc | quote }}
  {{- else if eq $storageType "s3" }}
  {{- if $storage.s3.secretkey }}
  AWS_SECRET_ACCESS_KEY: {{ $storage.s3.secretkey | b64enc | quote }}
  {{- end }}
  {{- else if eq $storageType "swift" }}
  OS_PASSWORD: {{ $storage.swift.password | b64enc | quote }}
  {{- else if eq $storageType "oss" }}
  ALIBABA_CLOUD_ACCESS_KEY_SECRET: {{ $storage.oss.accesskeysecret | b64enc | quote }}
  {{- end }}
  {{- if and .Values.chartmuseum.basicAuth.enabled ( eq .Values.chartmuseum.basicAuth.basicAuthPass "" ) }}
  BASIC_AUTH_PASS: {{ randAlphaNum 10 | b64enc | quote }}
  {{- else if .Values.chartmuseum.basicAuth.enabled }}
  BASIC_AUTH_PASS: {{ .Values.chartmuseum.basicAuth.basicAuthPass | b64enc | quote }}
  {{- end }}
  {{- if .Values.chartmuseum.enableTLS }}
  TLS_CERT: {{ .Files.Get "cert/tls.crt" | b64enc }}
  TLS_KEY:  {{ .Files.Get "cert/tls.key" | b64enc }}
  {{- end }}
{{- end }}
